### ISSUE TITLE
allow for initial organization/users creation

### ISSUE THREAD

**Issue by andrewelizondo** [chef-cookbooks/chef-server-cluster#35]
Remove the manual step of creating these by hand, we can utilize some cheffish to create these by what is defined in an attribute

**Comment by stephenlauck** [comment]
@andrewelizondo Are you thinking of maybe a hash with orgs and users set as an attribute? How would this work with Cheffish?

**Comment by tas50** [comment]
Closing as this cookbook has been deprecated
